# Schema for the configuration files of the System module.

feeds_crawler.settings:
  type: config_object
  label: 'Automatic Reference Settings'
  mapping:
    uuid:
      type: uuid
      label: 'Site UUID'
      constraints:
        Uuid: []
        NotNull: []
    status:
      type: boolean
      label: 'Compact mode'
    entity_type:
      type: sequence
      label: 'Entity Types'
      sequence:
        type: string

feeds_crawler.type.*:
  type: config_entity
  label: 'Feeds Crawler Type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'

feeds_crawler_attribute.type.*:
  type: config_entity
  label: 'Feeds Crawler Type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
